#!/usr/bin/env bash
# transfer a file to the server
#it Accepts two parameters:
#	-The path to the file to be transfered.
#	-The IP of the server we want to transfer the file to.
#	-The user name scp connects with.
#	-The path to the ssh priv key that scp uses.

if [ "$#" -eq 4 ]; then
	
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2:~/"

	else
		echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
