#!/usr/bin/env bash
# configures nginx server so that /redirect is redirecting
#to another page
#The redirect must be a 301 Moved Permanently

#update package lists
apt-get update

#Install nginx
apt-get install -y nginx

#create a back up of the original nginx.conf file
cp /etc/nginx/nginx.conf    /etc/nginx/nginx.conf.bak


#modify the nginx.conf file

new="
	server {
		location redirect_me{
				return "https://www.youtube.com/watch?v=QH2-TGUlwu4";
			}
		}
	}
	"
sed -i "/server {/a $new" /etc/nginx/nginx/nginx.conf

service nginx restart
