#!/usr/bin/env bash
#configures nginx server on ubuntu machine 
#so that /redirect_me redirects to another page.
#The redirection must be a 301 Moved Permanently

#update package lists
apt-get update

#Install nginx
apt-get install -y nginx

#/redirect_me redirects to another page
redirect="rewrite ^/redirect_me https://www.youtube.com permanent;"

sed -i '/server_name _;/a\\t'"$redirect" /etc/nginx/sites-enabled/default

#validate nginx configuration
nginx -t

#restart nginx
service nginx restart
