#!/usr/bin/env bash
#configures nginx server on ubuntu machine 
#so that /redirect_me redirects to another page.
#The redirection must be a 301 Moved Permanently

#update package lists
apt-get update

#Install nginx
apt-get install -y nginx

#create a back up of the original nginx.conf file
cp /etc/nginx/nginx.conf    /etc/nginx/nginx.conf.bak


#modify the nginx.conf file

new="
http {
	server {
		location {
			return Ceci n'est pas une page=404;
		}
	}
}
"

sed -i -e "s/$(sed -ne "1http" /etc/nginx/nginx.conf)/$new/" /etc/nginx/nginx.conf

#echo "$new" > /etc/nginx/nginx/nginx.conf

#validate nginx configuration
nginx -t

service nginx restart
