#!/usr/bin/env bash
#configures nginx server on ubuntu machine 
#the page must return HTTP 404 error code.
#The page must contain the string Ceci n'est pas une page.

#update package lists
apt-get update

#Install nginx
apt-get install -y nginx

#create a 404.html  file in html directory
echo "Ceci n'est pas une page" > /var/www/html/404.html

#add the error_page in sites-enabled directory
e="
	error_page 404 /404.html;
	location = /404.html {
      		root /var/www/html;
      		internal;
	}
"
#save the config to a temp file and insert them in default file
echo "$e" > temp.conf

sed -i '/listen 80 default_server;/r tmp.conf' /etc/nginx/sites-enabled/default

rm temp.conf

#validate nginx configuration
nginx -t

service nginx restart
