#!/usr/bin/env bash
#check if nginx is listening to port , check if it's running and start it if it's not and then curl localhost.
apt-get update
apt-get install nginx
apt-get install net-tools

netstat -lpdn

service nginx status
service nginx start
curl localhost
