#!/usr/bin/env bash
# This script checks if Nginx is listening on port 80,
# ensures it's running, and curls the server to verify its response.
apt-get update
apt-get install -y nginx
service nginx start