#!/usr/bin/env bash
# Bash script that displays lines containing the bash word,
# Thus allowing you to easily get the PID of your Bash process.
ps aux | grep bash | grep -v grep
shellcheck disable=SC2009