#!/usr/bin/env bash
# simple parsing of Apache log access files.
# Today the Customer Support department reported that a user reported that the # site is being “buggy”. Not being a detailed description, you want to have a l# ook at the Apache logs and gather data about the traffic.

# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

awk '{print $1, $9}' apache-access.log
