#!/usr/bin/env bash
# Displays Best School 10 times
# for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -le 9 ]; do
	if ((i==9)); then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
