#!/usr/bin/env bash
# Bash script that displays the content of the current directory.
# In a list format.

for file in *; do
	if [[ $file == .* ]]; then
		continue
	fi

	name_after_dash="${file#*-}"

	echo "$name_after_dash"
done
