#!/usr/bin/env bash
# Bash script that displays the content of the current directory.
# In a list format.

shopt -s extglob

LIST=$(ls)
for i in $LIST; do
	if [[ -f "$i" ]]; then
		echo "${i#[0-9]*-}"
	fi
done
