#!/usr/bin/env bash

#This script creates an RSA key pair
#Requirements:
#	-Name of created private key must be school
#	-Number of bits in the created key to be created 4096
#	-The created key must be protected by passphrase

priv_key="school"
pass_phrase="betty"

ssh-keygen -t rsa -b 4069 -N "$pass_phrase" -f "$priv_key" 
